<?php
/**
 * @author     The S Group <support@sashas.org>
 * @copyright  2020  Sashas IT Support Inc. (https://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<div>
    Device Name
    <input name="device_name" />
    <button id="add-new-device" type="submit" title="<?= $block->escapeHtmlAttr(__('Register device')) ?>"
            class="action primary">
        <span><?= $block->escapeHtml(__('Add a new device')) ?></span>
    </button>
</div>

<div>
    Registered Devices:
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "TheSGroup_WebAuthn/js/view/webAuthnRegister": {
            }
        }
    }
</script>
